ALTER TABLE Livratori
ADD CONSTRAINT PK_ID_LIVRATOR PRIMARY KEY ([ID Livrator])

ALTER TABLE Produse
ADD CONSTRAINT PK_ID_Produs PRIMARY KEY ([ID Produs])

ALTER TABLE [Categorie Produs]
ADD CONSTRAINT PK_ID_Categorie_Produs PRIMARY KEY ([ID Categorie Produs])

ALTER TABLE Discount
ADD CONSTRAINT PK_ID_DISCOUNT PRIMARY KEY ([ID Discount])

ALTER TABLE Clienti
ADD CONSTRAINT FK_ID_CLIENT PRIMARY KEY ([ID Client])

ALTER TABLE [Comanda Client]
ADD CONSTRAINT PK_ID_Comanda_Client PRIMARY KEY ([ID Comanda])

ALTER TABLE [Loc livrare]
ADD CONSTRAINT PK_ID_LIVRARE PRIMARY KEY ([ID])

ALTER TABLE Angajati
ADD CONSTRAINT PK_ID_ANGAJAT PRIMARY KEY ([ID Angajat])

ALTER TABLE Functie
ADD CONSTRAINT PK_ID_FUNCTIE PRIMARY KEY ([ID Functie])

ALTER TABLE Salariu
ADD CONSTRAINT PK_ID_SALARIU PRIMARY KEY ([ID Salariu])

ALTER TABLE [Functie Angajati]
ADD CONSTRAINT PK_ID_FUNCTIE_ANGAJAT PRIMARY KEY ([ID FUNCTIE ANGAJAT])

ALTER TABLE [Tip Clienti]
ADD CONSTRAINT PK_ID_TIP_CLIENT PRIMARY KEY ([ID Tip Client])

ALTER TABLE [Materie prima]
ADD CONSTRAINT PK_MAT_PRIMA PRIMARY KEY ([ID Marfa])

ALTER TABLE [Loc Aprovizionare]
ADD CONSTRAINT PK_ID_LOCALITATE PRIMARY KEY ([ID Localitate])

ALTER TABLE [Provenienta Materiale]
ADD CONSTRAINT PK_ID_LOCALITATE_MAT PRIMARY KEY ([ID Localitate])

ALTER TABLE Materiale
ADD CONSTRAINT PK_ID_Materiale PRIMARY KEY ([ID Material])

ALTER TABLE [Sursa Utilitati]
ADD CONSTRAINT PK_ID_SURSA_Utilitati PRIMARY KEY ([ID Sursa])

ALTER TABLE Utilitati
ADD CONSTRAINT PK_ID_Utilitati PRIMARY KEY ([ID Utilitati])

ALTER TABLE [Tip Materie Prima]
ADD CONSTRAINT PK_TIP_MAT_PRI PRIMARY KEY ([ID Tip Materie Prima])

-------------------------------------------

ALTER TABLE Functie
ADD CONSTRAINT FK_ID_SALARIU FOREIGN KEY ([ID Salariu]) REFERENCES Salariu ([ID Salariu])

ALTER TABLE [Comanda Detalii]
ADD CONSTRAINT FK_ID_Detalii_Comanda FOREIGN KEY ([ID Comanda]) REFERENCES [Comanda Client] ([ID Comanda])

ALTER TABLE [Comanda Detalii]
ADD CONSTRAINT FK_ID_PRODUS FOREIGN KEY ([ID Produs]) REFERENCES [Produse]([ID Produs])

ALTER TABLE [Comanda Detalii]
ADD CONSTRAINT FK_ID_DISCOUNT FOREIGN KEY ([ID Discount]) REFERENCES [Discount]([ID Discount])

ALTER TABLE [Comanda Client]
ADD CONSTRAINT FK_ID_Categorie_Produs FOREIGN KEY ([ID Categorie Produs]) REFERENCES [Categorie Produs]([ID Categorie Produs])

ALTER TABLE [Comanda Client]
ADD CONSTRAINT FK_ID_CLIENT_COMANDA FOREIGN KEY ([ID Client]) REFERENCES Clienti ([ID Client])

ALTER TABLE [Comanda Client]
ADD CONSTRAINT FK_ID_LIVRARE_COMANDA FOREIGN KEY ([ID Livrare]) REFERENCES [Loc Livrare] ([ID])

ALTER TABLE Produse
ADD CONSTRAINT FK_IF_Produs_Categorie FOREIGN KEY ([ID Categorie Produs]) REFERENCES [Categorie Produs]([ID Categorie Produs])

ALTER TABLE Clienti 
ADD CONSTRAINT FK_ID_TIP_CLIENT FOREIGN KEY ([ID Tip Client]) REFERENCES [Tip Clienti] ([ID Tip Client])

ALTER TABLE [Functie Angajati]
ADD CONSTRAINT FK_ANGAJAT_FUNCTIE_ANGAJAT FOREIGN KEY ([ID Angajat]) REFERENCES Angajati ([ID Angajat])

ALTER TABLE [Functie Angajati]
ADD CONSTRAINT FK_FUNCTIE_FUNCTIE_ANGAJAT FOREIGN KEY ([ID Functie]) REFERENCES Functie ([ID Functie])

ALTER TABLE [Materie prima]
ADD CONSTRAINT FK_MATERIE_P_APROVIZIONARE FOREIGN KEY ([ID Loc Aprovizionare]) REFERENCES [Loc Aprovizionare]([ID Localitate])

ALTER TABLE Materiale
ADD CONSTRAINT FK_MATERIALE_APROVIZIONARE FOREIGN KEY ([ID Loc Cumparare]) REFERENCES [Provenienta Materiale]([ID Localitate])

ALTER TABLE Utilitati
ADD CONSTRAINT FK_UTILITATI_APROVIZIONARE FOREIGN KEY ([ID Sursa]) REFERENCES [Sursa Utilitati]([ID Sursa])

ALTER TABLE  [Comanda Client]
ADD CONSTRAINT FK_ID_LIVRATOR FOREIGN KEY ([ID Livrator]) REFERENCES Livratori ([ID Livrator])

ALTER TABLE [Functie Angajati]
ADD CONSTRAINT FK_ID_SEF FOREIGN KEY ([ID Sef]) REFERENCES Angajati ([ID Angajat]) 

ALTER TABLE [Materie prima]
ADD CONSTRAINT FK_TIP_MAT_PRI FOREIGN KEY ([ID Tip Materie Prima]) REFERENCES [Tip Materie Prima] ([ID Tip Materie Prima])
